### ISSUE TITLE
Sincronizar datos de familiares en SAMAN

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/afiliacion#7]
Es necesario que los datos de los familiares incluidos en el sistema SSSIFANB sean incluidos en el sistema SAMAN de forma automática, al tiempo que se incluyen los datos del militar titular

**Comment by gesaodin** [comment]
Esta es una tarea del tunel :+1: 
Resuelta en Saman y Saman WEB 
Modulo del tunel/mdl/sssifanb/militar.go Lineas : ( 429 - 440)
func ActualizarPostgresSaman(d string) {
  _, err := sys.PostgreSQLSAMAN.Exec(d)
  if err != nil {
    fmt.Println("SAMAN: ", err.Error())
    return
  }
  _, err = sys.PsqlWEB.Exec(d)
  if err != nil {
    fmt.Println("SAMANWEB: ", err.Error())
    return
  }
}
