### ISSUE TITLE
Datos estadísticos de los afiliados al Instituto

### ISSUE THREAD

**Issue by informaticaipsfa** [informaticaipsfa/afiliacion#8]
Es necesario programar la interfaz y los reportes estadísticos referentes a la información del numero de afiliados al Instituto, considerando las diferentes clasificaciones de los afiliados.

1. Nº total de afiliados, clasificados en: militares activos, reserva activa, total de familiares, familiares de militares activos, familiares de personal de reserva activa, sobrevivientes, inválidos.
2. Nº total de Militares activos: clasificados por componentes, clasificados por componentes y grados, sexo
3. Nº total de carnets emitidos, clasificados por: militares activos, reserva activa, familiares, sobrevivientes, inválidos.
4. Nº de carnets emitidos por grados, por motivo, por sucursal

**Comment by gesaodin** [comment]
a4389761ea4694d1553fd53fc25d117d3625c539

Falta carnets

**Comment by gesaodin** [comment]
e9b0f2730d146c34688fc3027401b664826218e2
